version: 0.2

phases:
  build:
    commands:
      - printenv
      - cat $CODEBUILD_SRC_DIR/.git/HEAD
      - echo Build started on `date`
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
